version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    container_name: buyzone
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buyzone
    ports:
      - "3308:3306" # Puertos: 3308 en tu máquina → 3306 en el contenedor
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
