name: Run Tests and Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: buyzone
        ports:
          - 3308:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: |
          cd backend
          echo "DB_HOST=127.0.0.1" > .env
          echo "DB_PORT=3308" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASS=root" >> .env
          echo "DB_NAME=buyzone" >> .env
          echo "NODE_ENV=test" >> .env

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run unit tests only
        run: |
          cd backend
          npm run test:unit

      - name: Build Backend Docker Image
        run: docker build -t buyzone-backend ./backend

      - name: Build Frontend Docker Image
        run: docker build -t buyzone-frontend ./frontend
